baseURL = "https://math.iisc.ac.in/~gadgil/topology-2025/"
languageCode = "en-us"
title = "MA 231: Topology"
theme = "course"
buildFuture = "true"
[params]
    code = "MA 231"
    course = "Topology"
    term = "August 2025"
[markup.goldmark.renderer]
    unsafe= true